### PR TITLE
fix bug: context score does not affect token's tot_cost

### PR DESCRIPTION
**Pull request by 1215thebqtic**
solve the issue discussed here #956

### CODE REVIEW

**Comment by pengzhendong** [comment]
I will review this pr later.

**Comment by housebaby** [comment]
l got the problem, that  if the context_score is large, there will be duplicate words coming out

**Comment by housebaby** [comment]
<html>
<body>
<style> td {white-space:pre-wrap;border:1px solid #dee0e3;}</style><byte-sheet-html-origin data-id="97gV4SmcLv-1648449684374" data-version="3" data-is-embed="true">

bonus | 942fbf7aaaa5e33585d45f5043d5406e | ed759c45e0af0c195721eb8193841178
-- | -- | --
目标 | 呼叫姚祥鑫 | 打电话给于孟白
无热词 | 呼叫姚翔欣 | 打电话给余梦白
2 | 呼叫姚翔欣 | 打电话给于梦白
4 | 呼叫姚翔欣 | 打电话给于梦白
6 | 呼叫姚翔欣 | 打电话给于梦白
8 | 呼叫姚翔欣 | 打电话给于梦白
10 | 呼叫姚翔欣 | 打电话给于梦白
12 | 呼叫姚翔欣 | 打电话给于梦白
14 | 呼叫姚翔欣 | 打电话给于梦白
16 | 呼叫姚翔欣 | 打电话给于梦白
18 | 呼叫姚翔欣 | 打电话给于梦白
20 | 呼叫姚翔欣 | 打电话给于梦白
22 | 呼叫姚翔欣 | 打电话给于于孟
24 | 呼叫姚翔欣 | 打电话给于于孟
26 | 呼叫姚姚翔欣 | 打电话给于于于孟
28 | 呼叫姚姚翔欣 | 打电话给于于于孟
30 | 呼叫姚姚翔欣 | 打电话给于于孟孟白
32 | 呼叫姚姚翔欣 | 打电话给于于于白
34 | 呼叫姚姚翔欣 | 打电话给于于于于白
36 | 于呼叫于于于姚姚姚欣 | 打电话给于于于于白
38 | 于呼叫于于于姚姚姚于欣 | 于打电话于于于于孟孟于
40 | 于于于于于于于姚姚姚于欣于于于 | 于打于于于于电话给于姚白
42 | 于于于于叫姚祥鑫于于 | 于打于于于于于话给于于于孟白

</byte-sheet-html-origin>
</body>
</html>

**Comment by pengzhendong** [comment]
@1215thebqtic Same problem as above. Have you test that?

**Comment by pengzhendong** [comment]
@1215thebqtic Have you test above. I got more deletion errors.

**Pull request closed without merging**
