### PR TITLE
[runtime/gpu] Add GPU Hotwords

### PR DESCRIPTION
**Pull request by zwglory**
Support hotword boosting for offline or streaming WeNet ASR models on GPUs.

For more information regarding the `ctc_decoder`, please refer to：https://github.com/Slyne/ctc_decoder/pull/11

Here are our test results：

Tested ENV
* CPU：40 Core, Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
* GPU：NVIDIA GeForce RTX 2080 Ti

Hotwords file: https://huggingface.co/58AILab/wenet_u2pp_aishell1_with_hotwords/tree/main/models

[AISHELL-1 Test dataset](https://www.openslr.org/33/)

* Test set contains 7176 utterances (5 hours) from 20 speakers. 

| model (FP16)                 | RTF     | CER    |
|------------------------------|---------|--------|
| offline model w/o hotwords   | 0.00437 | 4.6805 |
| offline model w/  hotwords   | 0.00428 | 4.5841 |
| streaming model w/o hotwords | 0.01231 | 5.2777 |
| streaming model w/  hotwords | 0.01195 | 5.1850 |

[AISHELL-1 hostwords sub-testsets](https://www.modelscope.cn/datasets/speech_asr/speech_asr_aishell1_hotwords_testsets/summary)

* Test set contains 235 utterances with 187 entities words.

| model (FP16)               | Latency (s) | CER   | Recall | Precision | F1-score |
|----------------------------|-------------|-------|--------|-----------|----------|
| offline model w/o hotwords | 5.8673      | 13.85 | 0.27   | 0.99      | 0.43     |
| offline model w/  hotwords | 5.6601      | 11.96 | 0.47   | 0.97      | 0.63     |

Decoding result

| Label                | hotwords  | pred w/o hotwords            | pred w/ hotwords             |
|----------------------|-----------|------------------------------|------------------------------|
| 以及拥有陈露的女单项目          | 陈露        | 以及拥有**陈鹭**的女单项目              | 以及拥有**陈露**的女单项目              |
| 庞清和佟健终于可以放心地考虑退役的事情了 | 庞清<br/>佟健 | **庞青**和**董建**终于可以放心地考虑退役的事情了 | **庞清**和**佟健**终于可以放心地考虑退役的事情了 |
| 赵继宏老板电器做厨电已经三十多年了    | 赵继宏       | **赵继红**老板电器做厨店已经三十多年了        | **赵继宏**老板电器做厨电已经三十多年了        |

Refer to more results: https://huggingface.co/58AILab/wenet_u2pp_aishell1_with_hotwords/tree/main/results

Mainly developed by @FieldsMedal

### CODE REVIEW

**Review by yuekaizhang — COMMENTED** [review]
Nice work. Would you mind merging the hotwords directory such that it would become a default settings?
1. merge model_repo_hotwords with regular model repos.
2. merge hotwords/readme.md into gpu/readme.md using a new section ### hotwords
3. hotwords.yaml could be under model_repo_x/scoring/, however, default hotwords_path is None like lm_path.  In readme.md, set it to ./model_repo_x/scoring/hotwords.yaml to enable hotwords.
4. In this way, we may don't need convert_start_x.sh

**Review by yuekaizhang — COMMENTED** [review]
Nice work. Would you mind merging the hotwords directory such that it would become a default settings?
1. merge model_repo_hotwords with regular model repos.
2. merge hotwords/readme.md into gpu/readme.md using a new section ### hotwords
3. hotwords.yaml could be under model_repo_x/scoring/, however, default hotwords_path is None like lm_path.  In readme.md, set it to ./model_repo_x/scoring/hotwords.yaml to enable hotwords.
4. In this way, we may don't need convert_start_x.sh
5. Also, it would be better if you could upload the script to comput f1 to scripts/.

**Comment by zwglory** [comment]
> Also, it would be nice if you could upload the script to comput f1 to scripts/.

No problem, we are going to merge the hotwords directory and upload the f1 code.

**Comment by zwglory** [comment]
In the latest commit, we
1. remove the hotwords directory and merge it into regular model_repo_x; 
2. add hotwords evaluation script; 
3. update readme with hotwords usage and evaluation.

Please help us review this pr when you are free. Thanks♪(･ω･)ﾉ

**Review by yuekaizhang — APPROVED** [review]

**Comment by yuekaizhang** [comment]
Many thanks.

**Pull request merged**
