### PR TITLE
[wenet] modify - runtime/code/decoder more faster 

### PR DESCRIPTION
**Pull request by Sang-Hoon-Pakr**

### CODE REVIEW

**Comment by Sang-Hoon-Pakr** [comment]
3 month ago i reported a isssue that slow down when i inference on cpu/gpu.

some people told same issue, but we couldn't got a clear answer. 
just said before run when you use it. 

this code will make faster RTF. 

in my case RTF =0.3~0.34 when i use CPU.

**Comment by robin1001** [comment]
Great catch! Seems it disables some optimization so we get more speedup at the warmup at the begging. And I wonder what's the result for large(more than 1k) test?

**Comment by Sang-Hoon-Pakr** [comment]
@robin1001  Hello !  I appreciate for your interesting on my request. 

This modified code is effective when the number of data is small or during the initial setting process.

When I ran 10 data, the results of the version before the fixing are as follows. ( Korean, cpu run)
`I1124 08:00:16.674357   839 decoder_main.cc:180] Total: decoded 58555ms audio taken 336787ms.
I1124 08:00:16.674383   839 decoder_main.cc:182] RTF: 5.752
`
When I ran 10 data, the results of the version after the fixing are as follows. ( Korean, cpu run)
`I1129 02:02:42.593503   42019 decoder_main.cc:180] Total: decoded 58555ms audio taken 21379ms.
I1129 02:02:42.593533   42019 decoder_main.cc:182] RTF: 0.3651
`

When I ran 1000 data, the results of the version before the fixing are as follows. ( Korean, cpu run)
`I1124 07:50:12.064172   671 decoder_main.cc:180] Total: decoded 5479126ms audio taken 2391585ms.
I1124 07:50:12.064200   671 decoder_main.cc:182] RTF: 0.4365
`

When I ran 1000 data, the results of the version after the fixing are as follows. ( Korean, cpu run)
`I1129 05:45:54.035125   48537 decoder_main.cc:180] Total: decoded 5479126ms audio taken 1453860ms.
I1129 05:45:54.035238   48537 decoder_main.cc:182] RTF: 0.2653
`

there are no difference CER between original version and modified version. 
I think that this fixing version effective clearly. 
especially, it give more effect when you run the model on a server and inference the initial files.

**Comment by robin1001** [comment]
Great gain, thanks for the contribution.

**Review by robin1001 — APPROVED** [review]

**Comment by cdliang11** [comment]
Good job. It is valid during the initial stage.

When I ran 100 data, the results of the version before the fixing are as follows. (cpu run)
`I0228 09:51:54.538599 149817 decoder_main.cc:180] Total: decoded 612871ms audio taken 162357ms.`
`I0228 09:51:54.538676 149817 decoder_main.cc:182] RTF: 0.2649`

When I ran 100 data, the results of the version after the fixing are as follows. (cpu run)
`I0228 09:55:23.919065 252123 decoder_main.cc:180] Total: decoded 612871ms audio taken 130573ms.`
`I0228 09:55:23.919111 252123 decoder_main.cc:182] RTF: 0.2131`

When I ran 1000 data, the results of the version before the fixing are as follows. (cpu run)
`I0228 09:47:32.543869 110463 decoder_main.cc:180] Total: decoded 5733642ms audio taken 1267369ms.`
`I0228 09:47:32.543953 110463 decoder_main.cc:182] RTF: 0.221`

When I ran 1000 data, the results of the version after the fixing are as follows. (cpu run)
`I0228 09:13:07.766005 67222 decoder_main.cc:180] Total: decoded 5733642ms audio taken 1231720ms.`
`I0228 09:13:07.766032 67222 decoder_main.cc:182] RTF: 0.2148`

**Comment by Sang-Hoon-Pakr** [comment]
@cdliang11 Thanks you for your attention. 

is it the results of first inference, after run model on your cpu ?

when i started first inference after run model on my cpu 
The initial data of about 10 were very slow.

**Comment by cdliang11** [comment]
@Sang-Hoon-Pakr Yes, I used the same test method.

**Comment by Sang-Hoon-Pakr** [comment]
@cdliang11 

could you check number of thread  ?

that results depends on number of thread 
each thread initialized when it first time run. 

so, when i set thread num 10. i got a results as blow. 
github

**Pull request merged**
