### PR TITLE
[runtime] support read fst using mmap

### PR DESCRIPTION
**Pull request by mackong**
# Background
## the fst file
```
➜  lm git:(standalone) ll lm.fst
-rw-r--r-- 1 mackong mackong 12G Aug  3 10:09 lm.fst
```
## disk
```
➜  ~ lspci | grep SSD
04:00.0 Non-Volatile memory controller: SK hynix Gold P31 SSD
```

# READ mode
when use *READ* mode, we got the following performance
```
I0831 22:01:58.278613 14004 decoder_main.cc:180] Total: decoded 9550158ms audio taken 3076034ms.
I0831 22:01:58.278636 14004 decoder_main.cc:182] RTF: 0.3221
```
and the resource usage is
read

# MMAP mode
when use *MMAP* mode, we got the following performance
```
I0831 20:42:52.785739  8840 decoder_main.cc:180] Total: decoded 9550158ms audio taken 2995321ms.
I0831 20:42:52.785763  8840 decoder_main.cc:182] RTF: 0.3136
```
and the resource usage is
mmap

### CODE REVIEW

**Comment by robin1001** [comment]
Any performance benchmark?

**Comment by mackong** [comment]
> Any performance benchmark?

Updated a rough benchmark.

**Comment by robin1001** [comment]
There is no gain in our evaluation with smaller FST, I think it's better if we use ConstFst directly, please see https://groups.google.com/g/kaldi-help/c/4Sqw6vKu9CI

**Comment by mackong** [comment]
Yes, for small FST, no need to use mmap for memory save.

**Pull request closed without merging**
