### PR TITLE
[runtime] fix runtime structure

### PR DESCRIPTION
**Pull request by pengzhendong**

### CODE REVIEW

**Comment by robin1001** [comment]
Why change all directories to low case? It's better we keep it unchanged. GPU/IPU/XPU/BPU are in upper case, typically.

**Comment by pengzhendong** [comment]
> Why change all directories to low case? It's better we keep it unchanged. GPU/IPU/XPU/BPU are in upper case, typically.

Because `android` is low case, and I think the low case is convenient to use `cd` command. We can create the `README.md` under each folder to explain the meaning of GPU/IPU/XPU/BPU.

**Comment by robin1001** [comment]
okay!

**Review by robin1001 — APPROVED** [review]

**Comment by robin1001** [comment]
okay!

**Pull request merged**
