### PR TITLE
[examples] better results on wenetspeech using revised transcripts

### PR DESCRIPTION
**Pull request by xingchensong**
:warning:**quality is important than quantity**:warning:

see https://github.com/wenet-e2e/WenetSpeech/discussions/54 for more infos

|   Model   |  Dev | Test\_Net | Test\_Meeting | blankpenalty |                                                                                                                  
|:-------------------:|:----:|:---------:|:-------------:|:-----------:|
|  u2pp_conformer (original transcripts) | 8.37 % N=328207 C=302993 S=12556 D=12658 I=2253  |   9.02 % N=414285 C=379271 S=23881 D=11133 I=2365     |     15.52 % N=220358 C=187746 S=14507 D=18105 I=1596     | 0.0 |
|  -  | 7.10 % N=328207 C=308457 S=13211 D=6539 I=3537  |   8.83 % N=414285 C=381933 S=24810 D=7542 I=4215     |     13.63 % N=220358 C=194446 S=16232 D=9680 I=4132     | 2.5 |
|  u2pp_conformer (revised transcripts)      | 5.90 % N=328207 C=311721 S=14597 D=1889 I=2888 | 8.96 % N=414092 C=380232 S=27606 D=6254 I=3222 | 11.99 % N=220358 C=195808 S=18243 D=6307 I=1878   | 0.0 |
| [zipformer-M](https://github.com/k2-fsa/icefall/pull/1130) | 8.58 | 7.84 | 14.64 | 0.0 |
| - | 7.24 | 7.77 | 12.37 | 2.5 |

### CODE REVIEW

**Comment by xingchensong** [comment]
update whisper result:

|   Model   |  Dev | Test\_Net | Test\_Meeting |                                                                                                              
|:-------------------:|:----:|:---------:|:-------------:|
|  whisper (original text) | 7.27 % N=328207 C=308016 S=11392 D=8799 I=3672  |   7.90 % N=414097 C=383382 S=18954 D=11761 I=2018   |     13.00 % N=220358 C=194417 S=11788 D=14153 I=2705     |
|  whisper (fixed text)      | 4.66 % N=328207 C=315591 S=10352 D=2264 I=2692 | 6.54 % N=414092 C=389523 S=19101 D=5468 I=2513 | 8.84 % N=220358 C=202722 S=11296 D=6340 I=1839   |
| paraformer | 3.38 % N=328207 C=319078 S=8045 D=1084 I=1959 | 6.74 % N=414285 C=388817 S=20119 D=5349 I=2444 | 6.95 % N=220358 C=206461 S=9090 D=4807 I=1422 |

As you can see, the overall results are already very close to those of Paraformer. I believe that by adding more open-source data, Whisper can definitely achieve better performance than Paraformer.

**Review by whiteshirt0429 — APPROVED** [review]

**Comment by Ryuk17** [comment]
Any plan to release this trained model?

**Comment by xingchensong** [comment]
> Any plan to release this trained model?

目前效果还没全面超越paraformer，没有release的意义，另外听闻阿里有意发布更好的多语种模型，后续在那个更强的base模型上去调可能会更好

**Comment by xingchensong** [comment]
@Ryuk17 另外，现在在wenet训练200M级别的模型已经很高效了，8卡3090,3~4天就能跑出来上面的u2pp_conformer结果

**Comment by Ryuk17** [comment]
了解，谢谢

**Comment by wwfcnu** [comment]
> > Any plan to release this trained model?
> 
> 传了一个whipser的
> 
> 链接：https://pan.baidu.com/s/1R1mJyqc_MwKZy6Vn32Z3zA?pwd=171n 提取码：171n --来自百度网盘超级会员V6的分享

这个微调后的模型能重新转回到openai style的ckpt吗

**Comment by Zth9730** [comment]
> > > Any plan to release this trained model?
> > 
> > 
> > 传了一个whipser的
> > 链接：https://pan.baidu.com/s/1R1mJyqc_MwKZy6Vn32Z3zA?pwd=171n 提取码：171n --来自百度网盘超级会员V6的分享
> 
> 这个微调后的模型能重新转回到openai style的ckpt吗

https://github.com/wenet-e2e/wenet/blob/main/wenet/whisper/convert_whisper_to_wenet_config_and_ckpt.py#L199 参考这里是可以转回去的

**Comment by tongtongking** [comment]
I used your fine-tuned  model in aishell4 dataeset and converted it to a zip file, but I encountered an error during inference. I suspect that the inconsistency in the `units.txt` dictionary might be the cause. I was wondering if there is a publicly available `units.txt` for the fine-tuned Whisper-large-v3-wenetspeech-revised_transcripts.zip file or model? Thank you!
image

**Pull request merged**
