### PR TITLE
[ssl/bestrq] happy ending---stable training 

### PR DESCRIPTION
**Pull request by Mddct**

### CODE REVIEW

**Review by xingchensong — APPROVED** [review]

**Comment by ncakhoa** [comment]
@Mddct Can you explain when you stack fbank feature, why you change from normalizing freq dimension to time dimension and please provide some training results for comparing two approaches. I think normalizing freq dimension is more correct than time dimension, since the model wants to learn local distributions.

**Comment by Mddct** [comment]
Thank you for your attention

截屏2024-08-19 11 55 32

The normalization of input is just to get richer codes id. The stack input dim=T is normalized here to simulate the calculation method of cmvn of stack input, and experiments show that this normalization will be better than norm. d has a larger proportion of unique codes

**Comment by Mddct** [comment]
> @Mddct Can you explain when you stack fbank feature, why you change from normalizing freq dimension to time dimension and please provide some training results for comparing two approaches. I think normalizing freq dimension is more correct than time dimension, since the model wants to learn local distributions.



> @Mddct Can you explain when you stack fbank feature, why you change from normalizing freq dimension to time dimension and please provide some training results for comparing two approaches. I think normalizing freq dimension is more correct than time dimension, since the model wants to learn local distributions.

Thank you for your attention

截屏2024-08-19 11 55 32

The normalization of input is just to get richer codes id. The stack input dim=T is normalized here to simulate the calculation method of cmvn of stack input, and experiments show that this normalization will be better than norm. d has a larger proportion of unique codes

**Comment by ncakhoa** [comment]
Can you show proportion of unique codes in two approaches. Also, have you tried to downstream model.

**Comment by Mddct** [comment]
> Can you show proportion of unique codes in two approaches. Also, have you tried to downstream model.

Yes, some promising results will be released recently.

**Pull request merged**
