### PR TITLE
[runtime] upgrade libtorch version to 2.1.0

### PR DESCRIPTION
**Pull request by xingchensong**
try to fix https://github.com/wenet-e2e/wenet/issues/2417  && https://github.com/wenet-e2e/wenet/issues/2393

#  TODO
- [x] pass compilation
    - [x] linux cpu
    - [x] linux gpu
    - [x] windows
    - [x] macos
    - [ ] android libtorch (next PR)
- [x] wer verification
- [x] speed comparison with 1.13.0

| libtorch | aishell-1 test (chunk 16 left -1, ctc greedy search) | rtf |
|------|-----|------|
| 2.1.0+cpu | 5.87 % N=104765 C=98725 S=5892 D=148 I=107 | 0.04972 (int8) |
| 2.1.0+gpu | 5.80 % N=104765 C=98786 S=5833 D=146 I=101  | 0.07579 (fp32) |
| 1.13.0+cpu | 5.85 % N=104765 C=98746 S=5871 D=148 I=110 | 0.05211 (int8) |

### CODE REVIEW

**Comment by xingchensong** [comment]
why c++17?

img_v3_0293_4d9542d4-cab6-41ba-a21c-ea224d52d8ag

**Comment by Mddct** [comment]
https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/encoder.py#L265

记得这里 att mask to bias， sdpa的bool的mask 算的不太对（batch下不太对， 单条的不确定要不要to bias），

**Comment by xingchensong** [comment]
> https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/encoder.py#L265
> 
> 记得这里 att mask to bias， sdpa的bool的mask 算的不太对（batch下不太对， 单条的不确定要不要to bias），

jit下用不到attention mask，哪个一直都是 torch.empty((0, 0, 0))，因为cache和current chunk都是valid

**Comment by xingchensong** [comment]
Why have we chosen libtorch 2.1.0 over the 2.1.2 version, which is in strict alignment with the PyTorch version?

As of March 19, 2024, libtorch 2.1.0 represents the latest available release for download from the official repository at https://download.pytorch.org/libtorch/cpu

**Review by Mddct — APPROVED** [review]

**Pull request merged**
