### PR TITLE
Contrastive learning for unified models

### PR DESCRIPTION
**Pull request by YYTtyy**
Hi,
This PR is the implementation of the INTERSPEECH 2023 paper Enhancing the Unified Streaming and Non-streaming Model with Contrastive Learning
Arxiv：https://arxiv.org/abs/2306.00755

Details:
add joint training  & contrastive loss for unified models (in ctl_model/asr_model_ctl.py)
add pure full-context mode forward (in ctl_model/encoder.py)
only return chunk size 1~25 for training (in ctl_model/mask.py)

The results on the AISHELL-1 dataset from the literature are as follows:
image

In addition, we conducted experiments on the in-house corpus, which contains 25000 hours of Mandarin speech data.  The results show that our method makes consistent improvements on the larger dataset. This table shows the results on the test set.
|  Models  |  Chunk=-1  |  Chunk=16  |
| :- | :- | :- |
|  U2 model  |  17%  |  18.8%  |
|  Ours  |  16.7%  |  18.2%  |

### CODE REVIEW

**Comment by xingchensong** [comment]
感谢 ！ 几点小建议

1. `wenet/ctl_model/mask.py` （左）似乎没有修改必要？看diff和 `wenet/utils/mask.py` （右） 其实是基本一样的（少了一个if分支）
6ed102f9-9f28-41fb-b724-43a4bf5889a7

2. `wenet/ctl_model/encoder.py` （左）可以直接继承 `wenet/transformer/encoder.py` （右）， 因为看代码相当于在BaseEncoder这个类上追加了一个成员函数`forward_full`且没有其他删除操作。继承的方式可以参考 https://github.com/wenet-e2e/wenet/blob/main/wenet/paraformer/layers.py#L207-L298
dc72a9e7-746e-4021-8799-850f78c2de7b

3. 可以rebase一下代码，最近training pipeline做了修改，`train.py`的大部分代码都挪到了`train_utils.py`,这个PR的相应修改可以酌情挪到train_utils, https://github.com/wenet-e2e/wenet/pull/2055

**Comment by YYTtyy** [comment]
好的没问题！感谢建议～

**Comment by xingchensong** [comment]
great work ! pr is quite clear，期待后续推送文章！

**Review by xingchensong — APPROVED** [review]

**Comment by kobenaxie** [comment]
有训练的loss曲线可以参考吗

**Comment by junshipeng** [comment]
ctl模型看起来有bug：

**Comment by junshipeng** [comment]
ctl模型运行有bug
  File "***/wenet/utils/executor.py", line 136, in cv
    ) if _dict['th_accuracy'] is not None else 0.0)
KeyError: 'th_accuracy
asr_model_ctl.py文件中的forward函数没有返回th_accuracy，导致报错

**Pull request merged**
