### PR TITLE
try to solve the programm stuck, when train and cv both are dynamic batch size

### PR DESCRIPTION
**Pull request by zelda3721**
try to solve the programm stuck, when train and cv both are dynamic batch size,according to the issue 
https://github.com/wenet-e2e/wenet/issues/842#issue-1072991518

### CODE REVIEW

**Comment by robin1001** [comment]
Why it is stuck for dynamic batch size?

**Comment by zelda3721** [comment]
> 

Mybe it is because the iteration counts are not always equals between processes, and why this happened may because the data is not balance. 
In my situation, I used my own data  with many short words, and trained with mult_cn dataset. When the stuck happened, there are also many defunct processes.

**Comment by robin1001** [comment]
Acctually, we use model.join() to process uneven data, please see https://pytorch.org/tutorials/advanced/generic_join.html

**Comment by robin1001** [comment]
Fixed in a simple way, please see https://github.com/wenet-e2e/wenet/pull/903/

**Pull request closed without merging**
