### PR TITLE
update markdown

### PR DESCRIPTION
**Pull request by DaobinZhu**
update markdown --stop-stage to --stop_stage

### CODE REVIEW

**Comment by robin1001** [comment]
stop-stage can not work?

**Comment by DaobinZhu** [comment]
I saw run.sh it was confusing because in run.sh it was $stop_stage but we typed stop-stage.
&nbsp;


1169213632
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binbin ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenet-e2e/wenet] update markdown (PR #1592)





 
stop-stage can not work?

**Comment by DaobinZhu** [comment]
Maybe we can unify this variable so that no one feel confusing.



&nbsp;


1169213632
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binbin ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenet-e2e/wenet] update markdown (PR #1592)





 
stop-stage can not work?

**Comment by robin1001** [comment]
okay, sounds reasonable.

**Review by robin1001 — APPROVED** [review]

**Pull request merged**
