### PR TITLE
Fix eot

### PR DESCRIPTION
**Pull request by Qiaochu-Song**
There is a bug when generating train.yaml from whisper checkpoint. Eot was using the token index of sot, and this pr fixes that.

### CODE REVIEW

**Comment by xingchensong** [comment]
good catch! How did you find it? Does it affect trainining results?

**Review by xingchensong — APPROVED** [review]

**Comment by Qiaochu-Song** [comment]
> good catch! How did you find it? Does it affect trainining results?

I was trying to convert and load whisper into wenet, then tried some samples without any fine-tuning. I was expecting it to give some reasonable outputs. However it did not stop decoding, even after <eot> was produced. Other than that the transcription looks correct. After changing eot to the correct idx, wenet decoding functions is able to terminate decoding correctly. 

Regarding effects on finetuning, I have not test it yet, but I assume it might affect training results a bit, but should not be too much, as tokens after <eot> won't be penalized in training.

**Comment by xingchensong** [comment]
I see, THX !!!

**Comment by xingchensong** [comment]
I can confirm that this fix does not affect training result.

- green: eot is 50258
- red: eot is 50257

image

**Pull request merged**
